USE GD1C2020

SELECT CLIENTE_DNI, COUNT(*) FROM gd_esquema.Maestra
GROUP BY CLIENTE_DNI
HAVING COUNT(*) > 1

SELECT CLIENTE_DNI, CLIENTE_APELLIDO, CLIENTE_NOMBRE FROM gd_esquema.Maestra
WHERE CLIENTE_DNI = '65334031'

SELECT ESTADIA_CODIGO, COUNT(*) FROM gd_esquema.Maestra
GROUP BY ESTADIA_CODIGO
HAVING COUNT(*) > 0
ORDER BY COUNT(*)

SELECT AVION_IDENTIFICADOR, AVION_MODELO, COUNT(*), VUELO_CODIGO FROM gd_esquema.Maestra
GROUP BY AVION_IDENTIFICADOR, AVION_MODELO, VUELO_CODIGO
HAVING COUNT(*) > 1
ORDER BY VUELO_CODIGO

SELECT  DISTINCT RUTA_AEREA_CODIGO, RUTA_AEREA_CIU_ORIG, RUTA_AEREA_CIU_DEST FROM gd_esquema.Maestra
WHERE RUTA_AEREA_CODIGO IS NOT NULL
ORDER BY RUTA_AEREA_CODIGO

SELECT DISTINCT RUTA_AEREA_CODIGO, COUNT(*) FROM gd_esquema.Maestra
GROUP BY RUTA_AEREA_CODIGO

SELECT BUTACA_NUMERO, BUTACA_TIPO, VUELO_CODIGO, AVION_IDENTIFICADOR, AVION_MODELO, FACTURA_NRO FROM gd_esquema.Maestra